restart_file: .na
start_datetime: 2026-06-18 00:00:00
end_datetime: .na
forecast_start_datetime: 2026-06-21 00:00:00
forecast_horizon: 14
sim_name: flare_glm_v4_gefs_seamless
configure_flare: configure_flare_glm.yml
use_s3: true
use_faasr: false
