on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 13 * * *"

name: flare_glm_v4

jobs:
  run_forecast:
    runs-on: ubuntu:latest
    container:
      image: rqthomas/flare-rocker:4.0.3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: install deps
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        shell: Rscript {0}
        run: |
          install.packages('rLakeAnalyzer')
          remotes::install_github("flare-forecast/ropenmeteo")

      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  Rscript $GITHUB_WORKSPACE/workflows/glm_flare_v4/forecast_workflow.R

